from __future__ import annotations

import argparse
import os
import shutil
import sys
import tempfile
import textwrap
from pathlib import Path, PurePosixPath
from uuid import uuid4


REPO_ROOT = Path(__file__).resolve().parents[1]
PACKAGE_DIR = REPO_ROOT / "causalis"
OUTPUT_DIR = REPO_ROOT / "notebooks" / "api"
HTML_OUTPUT_DIR = OUTPUT_DIR / "html"


def _relative_posix_path(path: Path, start: Path) -> str:
    return PurePosixPath(
        os.path.relpath(os.path.realpath(path), os.path.realpath(start))
    ).as_posix()


def _require_docs_dependencies():
    try:
        from sphinx.cmd.build import build_main
    except ImportError as exc:  # pragma: no cover - exercised via subprocess
        raise SystemExit(
            "Missing documentation dependencies. Install them with "
            "`pip install -e .[docs]` or `pip install sphinx myst-parser sphinx-autodoc2`."
        ) from exc

    return build_main


def _write_conf_py(source_dir: Path) -> None:
    package_path = _relative_posix_path(PACKAGE_DIR, source_dir)
    conf_text = textwrap.dedent(
        f"""
        extensions = [
            "myst_parser",
            "autodoc2",
        ]

        project = "Causalis API Reference"
        root_doc = "reference"
        source_suffix = {{
            ".md": "markdown",
        }}
        exclude_patterns = ["_build"]
        html_copy_source = True

        autodoc2_packages = [
            {{
                "path": {package_path!r},
                "module": "causalis",
            }},
        ]
        autodoc2_output_dir = "apidocs"
        autodoc2_render_plugin = "myst"
        # Only the root package requires __all__. Many child modules have no
        # __all__, and static analysis cannot resolve every lazy re-export.
        autodoc2_module_all_regexes = [r"causalis"]
        # Preserve the existing MyST docstring rendering. The former escaped
        # regex never selected child docstrings for RST parsing. A migration
        # to NumPy/RST needs a separate review of the mixed-format corpus.
        autodoc2_docstring_parser_regexes = []
        autodoc2_hidden_objects = ["private", "inherited"]

        """
    ).strip()
    (source_dir / "conf.py").write_text(conf_text + "\n", encoding="utf-8")


def _write_reference_page(source_dir: Path) -> None:
    reference_text = textwrap.dedent(
        """
        # API Reference

        This page is auto-generated by `scripts/generate_api_reference.py`.

        ```{toctree}
        :maxdepth: 2
        :titlesonly:

        apidocs/index
        ```
        """
    ).lstrip()
    (source_dir / "reference.md").write_text(reference_text, encoding="utf-8")

    apidocs_dir = source_dir / "apidocs"
    apidocs_dir.mkdir()
    apidocs_index_text = textwrap.dedent(
        """
        # API Modules

        ```{toctree}
        :maxdepth: 3
        :titlesonly:

        causalis/causalis
        ```
        """
    ).lstrip()
    (apidocs_dir / "index.md").write_text(apidocs_index_text, encoding="utf-8")


def _build_staged_output(output_dir: Path) -> Path:
    build_main = _require_docs_dependencies()

    with tempfile.TemporaryDirectory(prefix="generate_api_reference_") as tmp_dir:
        temp_root = Path(tmp_dir)
        source_dir = temp_root / "source"
        build_dir = temp_root / "build"
        source_dir.mkdir()
        build_dir.mkdir()

        _write_conf_py(source_dir)
        _write_reference_page(source_dir)

        result = build_main([
            "-W", "--keep-going", "-b", "html", str(source_dir), str(build_dir)
        ])
        if result != 0:
            raise RuntimeError(f"Sphinx build failed with exit code {result}.")

        generated_apidocs = source_dir / "apidocs"
        if not generated_apidocs.is_dir():
            raise FileNotFoundError(f"Expected generated docs at {generated_apidocs}.")

        staged_output = output_dir.parent / f".{output_dir.name}.staged-{uuid4().hex}"
        staged_output.mkdir(parents=True)
        try:
            shutil.copytree(build_dir, staged_output / "html")
        except BaseException:
            shutil.rmtree(staged_output)
            raise

    return staged_output


def _swap_output_dir(staged_output: Path, output_dir: Path) -> None:
    backup_dir = output_dir.parent / f".{output_dir.name}.backup-{uuid4().hex}"
    had_previous_output = output_dir.exists()

    if had_previous_output:
        os.replace(output_dir, backup_dir)

    try:
        os.replace(staged_output, output_dir)
    except Exception:
        if had_previous_output and backup_dir.exists() and not output_dir.exists():
            os.replace(backup_dir, output_dir)
        raise
    else:
        if backup_dir.exists():
            shutil.rmtree(backup_dir)


def generate_api_reference(output_dir: Path | None = None) -> Path:
    if not PACKAGE_DIR.is_dir():
        raise FileNotFoundError(f"Package directory not found: {PACKAGE_DIR}")

    output_dir = OUTPUT_DIR if output_dir is None else Path(output_dir).resolve()
    # Publishing replaces the entire destination tree. Never allow an ancestor
    # of the checked-out package (including the repository itself) as output.
    package_dir = PACKAGE_DIR.resolve()
    destination = output_dir.resolve()
    if (destination == package_dir or destination in package_dir.parents
            or package_dir in destination.parents):
        raise ValueError("Output directory must not contain the package source.")
    output_dir.parent.mkdir(parents=True, exist_ok=True)
    staged_output = _build_staged_output(output_dir)
    try:
        _swap_output_dir(staged_output, output_dir)
    finally:
        if staged_output.exists():
            shutil.rmtree(staged_output)
    return output_dir / "html"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build the API reference; Sphinx warnings fail the build.")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--output-dir", type=Path, help="Replace this directory with the generated reference.")
    mode.add_argument("--check", action="store_true", help="Build in a temporary directory without publishing HTML.")
    options = parser.parse_args(argv)
    if options.check:
        with tempfile.TemporaryDirectory(prefix="check_api_reference_") as tmp_dir:
            generate_api_reference(Path(tmp_dir) / "api")
        print("API reference build check passed (warnings are errors).")
    else:
        html_dir = generate_api_reference(options.output_dir)
        print(f"Generated HTML API reference in {html_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
